// LANGUAGES:
module.exports.langNames = {
    "en": "English",
    "es": "Español",
    "de": "Deutsch",
    "nl": "Nederlands",
    "kr": "한국어",
    "pr": "Português",
    "jp": "日本語",
    "fr": "Français",
    "fi": "Suomi",
    "zh": "简体中文",
    "zhtr": "繁體中文",
    "pl": "Polski",
    "hi": "हिन्दी",
    "ru": "Pусский",
    "it": "Italiano",
    "tg": "Tagalog",
    "tr": "Türkçe",
}
