module.exports = `
menu.btn.ranked 排位赛
menu.btn.shop 商城
menu.btn.social 社区
menu.btn.maps 游戏
menu.btn.mods 模组
menu.btn.settings 设定
menu.btn.customize 自定义
menu.btn.invite 邀请
menu.btn.invite.clicked 已复制
menu.btn.join 加入游戏房间
menu.btn.host 创建游戏房间
menu.btn.browser 浏览服务器
generic.wait 请稍等...
generic.loading 加载中...
generic.none 无
generic.connecting 连接中...
generic.select 选择
generic.delete 删除
generic.save 保存
generic.load 载入
generic.search 搜索
generic.leave 退出
generic.default 默认
generic.submit 提交
generic.create 创建
generic.random 随机
generic.failed 失败
generic.success 成功!
generic.name 用户名
generic.level 等级
generic.score 得分
generic.off 关
generic.defeat 失败
generic.victory 胜利
generic.matchover 比赛结束
generic.matchaband 比赛被迫终止
generic.follow 关注
generic.unfollow 取消关注
generic.followers 追随者
generic.following 关注中
generic.games 游戏
generic.wins 胜场
generic.lose 败场
generic.clan 战队
generic.games.played 已玩游戏数
generic.games.won 胜场数
generic.games.lost 败场数
generic.timep 游玩时间
generic.kills 击杀数
generic.deaths 死亡数
generic.kdr KDR(击杀/死亡比例)
generic.time 时间
generic.logout 注销
generic.logout.sessions 为所有设备注销
generic.username 输入用户名
generic.password 输入密码
generic.register 注册
generic.login 登录
generic.accuracy 命中率
player.waiting 等待更多玩家加入
player.died 死亡
player.killed 被此玩家击杀
player.killstreak {0} 正在 {1} 连杀
player.inactive 由于不活跃,游戏已断开连接
player.disconnect 连接已断开
timer.end 下一场将在 {0} 后开始
leaderboard.empty 空房间
popup.checkpoint 检查点!
app.play 点此开始游戏
app.spectate 点此处观战
app.play.mobile 点击屏幕开始游戏
app.spectate.mobile 点击屏幕开始观战
app.play.controller 按下开始游戏
app.spectate.controller 按下开始观战
purchase.error 出现错误
purchase.error.click 点此</a> 并重试!
purchase.error.limit 您可能已超出每日交易限额
settings.reset 重设
settings.reset.confirm 您是否希望重置所有设定?
settings.import 导入
settings.export 导出
settings.none 没有找到该设置
settings.backup 备份设置
settings.controls.change 按键绑定
settings.controls.press 按下任意按键
settings.local.header 本地化 <span id="requiresRestart"><span style="color: #eb5656">*</span> 需要重启游戏</span>
settings.local.region 默认区域
settings.local.lang 语言
settings.network.header 网路
settings.network.sendRate 高服务器应答率
settings.network.netRerouting 自动
settings.network.lagComp 延迟修正(Lag Compensation)
settings.popup.header Popups 弹窗
settings.popup.freeKRPop Show Free KR Popup 免费KR弹窗
settings.experimental.header 实验性功能
settings.experimental.aimFreezeFix ADS(瞄准)冻结修复
settings.experimental.mouseFlickFix Mouse Flick Fix 视野跳动修复
settings.experimental.shaderRendering Instance Rendering
settings.dev.header Developer
settings.dev.forceUpdate Force Update Skins
settings.dev.forceRegen Always Regenerate Player
settings.dev.extraBan Extra Ban Info
settings.chat.header 聊天
settings.chat.chat 显示聊天窗口
settings.chat.chat.all 总是
settings.chat.chat.focus 仅限关注时显示
settings.chat.messages 显示玩家消息
settings.chat.unboxings 显示玩家开箱
settings.chat.chatOp 聊天窗口透明度
settings.chat.chatBGOp 聊天窗口背景透明度
settings.chat.chatHeight 聊天窗口高度
settings.chat.chatTimer 消息显示时间
settings.chat.chatTextOutline 消息文字轮廓
settings.chat.chatFilter 不良语言过滤(仅限英文)
settings.quality.header 游戏性能
settings.quality.updRate 帧数限制
settings.quality.rendDst 渲染距离
settings.quality.res 分辨率
settings.quality.part 颗粒效果
settings.quality.mapDet 地图细节
settings.quality.noTex 无贴图
settings.quality.partdist 粒子渲染距离
settings.quality.renderdist 渲染距离
settings.quality.reflection Reflection Quality 光线反射
settings.quality.antiAlias 反锯齿
settings.quality.shadows 阴影
settings.quality.softShad 软阴影
settings.quality.highResShad 高分辨率阴影
settings.quality.shadowsDynamic 动态阴影
settings.quality.trails 其他玩家弹道轨迹
settings.quality.yourTrails 玩家自身弹道轨迹
settings.quality.mflash 枪口火焰
settings.quality.flap 狙击枪瞄准镜保护盖
settings.quality.lowSpec 低配置模式
settings.quality.ambient 环境阴影
settings.quality.ambientOld Old Shading (When Possible)
settings.quality.textureAnim 纹理动画
settings.quality.objectAnim 物体动画
settings.quality.screenShake 屏幕晃动
settings.quality.weaponShine 武器光泽
settings.quality.rendGamma Gamma
settings.quality.lighting 光照效果
settings.quality.showExplo 显示爆炸特效
settings.quality.aspectRatio 屏幕高宽比
settings.post.header 后期处理
settings.post.post 后期处理
settings.post.bloom Bloom
settings.post.bloomThreshold Bloom Threshold
settings.post.bloomStrength Bloom Strength
settings.post.bloomRadius Bloom Radius
settings.post.ssao SSAO
settings.post.ssaoRadius SSAO Radius
settings.interface.hitInd 伤害指示器
settings.interface.hitColor 伤害指示颜色
settings.interface.dmg 显示伤害
settings.interface.dmgCol 伤害颜色
settings.interface.critCol 暴击颜色
settings.interface.header 界面
settings.interface.scale 用户界面比例
settings.interface.ui 显示用户界面
settings.interface.scoreboard 使用经典计分板
settings.interface.oldBrowser 使用经典浏览器
settings.interface.rarityanim 禁用稀有物品动画
settings.interface.showPfp 显示用户头像
settings.interface.showTradeMsg 显示交易信息
settings.interface.hp 动态血条(HP)
settings.interface.dmgScale 伤害显示比例
settings.interface.killf 显示击杀列表
settings.interface.ping 显示网络延迟
settings.interface.net-stats 显示网络状况
settings.interface.fps 显示帧数
settings.interface.deaths 显示死亡数
settings.interface.kd 显示KD
settings.interface.kills 显示击杀数
settings.interface.streak 显示连杀数
settings.interface.score 显示分数
settings.interface.spectators 显示观战者数量
settings.interface.speed 显示移动速度
settings.interface.speedOffX 移动速度水平位置
settings.interface.speedOffY 移动速度垂直位置
settings.interface.speedOpacity 速度显示透明度
settings.interface.speedScale 速度显示比例
settings.interface.speedColor 当前速度颜色
settings.interface.speedColorMax 最高速度颜色
settings.interface.medals 显示勋章
settings.interface.hideNames 显示名牌
settings.interface.hideNames.team 名牌仅限队友
settings.interface.hideNames.enemy 名牌仅限敌人
settings.interface.hideNames.all 所有人均显示名牌
settings.interface.nametagStyle 名牌样式
settings.interface.nametagOpac 名牌透明度
settings.interface.nametagStyle.health 仅限血条(HP)
settings.interface.nametagStyle.name 仅限用户名
settings.interface.nametagStyle.nameLvl 用户名和血条(HP)
settings.interface.nametagStyle.all 所有
settings.interface.healthNum 名牌
settings.interface.healthColT 队友血条(HP)颜色
settings.interface.healthColE 敌人血条(HP)颜色
settings.interface.xpBarCol 经验条颜色
settings.interface.xpBarOpac 经验条透明度
settings.crosshair.header 准星
settings.crosshair.type 种类
settings.crosshair.type.2 自定义
settings.crosshair.type.3 叠层
settings.crosshair.type.4 图片
settings.crosshair.type.5 精准
settings.crosshair.style 样式
settings.crosshair.style.0 十字
settings.crosshair.style.1 空心圆
settings.crosshair.style.2 实心圆
settings.crosshair.style.3 空心方块
settings.crosshair.style.4 实心方块
settings.crosshair.image 图片
settings.crosshair.image.paste 准星图片
settings.crosshair.always 总是显示
settings.crosshair.color 颜色
settings.crosshair.shadow.color 阴影颜色
settings.crosshair.shadow.thickness 阴影粗细
settings.crosshair.size 尺寸
settings.crosshair.thickness 粗细
settings.crosshair.gap 中心间隔大小
settings.crosshair.dot 点
settings.crosshair.opacity.use 使用自定义透明度
settings.crosshair.opacity.custom 自定义透明度
settings.hitmarker.header 命中标记
settings.hitmarker.color 颜色
settings.hitmarker.kcolor 击杀颜色
settings.hitmarker.thickness 粗细
settings.hitmarker.opacity 透明度
settings.hitmarker.leng 长度
settings.hitmarker.spacing 间距
settings.hitmarker.animD 动画尺寸
settings.hitmarker.animS 动画速度
settings.hitmarker.hitm 显示
settings.hitmarker.hitmFad 褪去速度
settings.hitmarker.custom 命中标记图标
settings.hitmarker.custom.paste 命中标记图标网址
settings.onKillS.style.0 默认
settings.onKillS.style.1 降低分辨率
settings.onKillS.style.2 降低FOV
settings.onKillS.style.3 增加FOV
settings.serverb.header 游戏房间浏览器
settings.serverb.oldBrowser 经典房间浏览器
settings.serverb.defaultRegionOnly 只显示默认地区的房间
settings.gameprivacy.header 游玩隐私
settings.gameprivacy.streamer 主播模式
settings.gameprivacy.anon 匿名模式
settings.gameprivacy.hideGameTitle 隐藏游戏标志
settings.gameplay.header 游戏性
settings.gameplay.sensitivityX X轴灵敏度
settings.gameplay.sensitivityY Y轴灵敏度
settings.gameplay.aimsensX ADS(瞄准)X轴灵敏度
settings.gameplay.aimsensY ADS(瞄准)Y轴灵敏度
settings.gameplay.challenge 挑战模式
settings.gameplay.invert 反转Y轴
settings.gameplay.onkillS 击杀
settings.gameplay.scrollDir 鼠标滚轮方向
settings.controller.header 手柄
settings.controller.sensitivityX X轴灵敏度
settings.controller.disableCons 禁用手柄
settings.controller.sensitivityY Y轴灵敏度
settings.controller.aimsensX ADS(瞄准)X轴灵敏度
settings.controller.aimsensY ADS(瞄准)Y轴灵敏度
settings.controller.deadZoneL 手柄摇杆死区 (左)
settings.controller.deadZoneR 手柄摇杆死区 (右)
settings.controller.triggerThres 触发阈值
settings.controller.vibration 震动
settings.controller.gradSpeed 渐缓速度
settings.controller.invert 反转Y轴
settings.mobile.header 移动设备
settings.mobile.sensitivityX X轴灵敏度
settings.mobile.sensitivityY Y轴灵敏度
settings.mobile.aimsensX ADS(瞄准)X轴灵敏度
settings.mobile.aimsensY ADS(瞄准)Y轴灵敏度
settings.mobile.vibration 震动
settings.mobile.gradSpeed 渐缓速度
settings.mobile.invert 反转Y轴
settings.audio.header 音效
settings.audio.sound 主音量
settings.audio.ambient 环境背景音量
settings.audio.voice 语言音量
settings.audio.weps 武器音量
settings.audio.player 玩家音量
settings.audio.skin 玩家服饰音量
settings.audio.ui 用户界面音量
settings.audio.asset Asset Volume
settings.audio.dialogue 动作音量
settings.viewmodel.header 视角
settings.viewmodel.fov 腰射视野
settings.viewmodel.fps 帧数
settings.viewmodel.bobbing 武器晃动
settings.viewmodel.leaning 武器倾斜
settings.viewmodel.show.primary 显示主武器
settings.viewmodel.show.secondary 显示副武器
settings.viewmodel.roundArms 圆形手臂
settings.viewmodel.show.melee 显示近战武器
settings.viewmodel.show.ads 开镜时隐藏武器
settings.viewmodel.toggleAim 松手时保持开镜
settings.viewmodel.show.hands 显示手部
settings.viewmodel.leftHand 左手持枪
settings.viewmodel.aimAnim 武器开镜动画
settings.viewmodel.rot 武器旋转
settings.viewmodel.xOff 武器X轴坐标 (左/右）
settings.viewmodel.yOff 武器Y轴坐标（上/下）
settings.viewmodel.zOff 武器Z轴坐标（前/后）
settings.viewmodel.weapSwapY 切换武器时武器的垂直位置
settings.viewmodel.weapReloadY 换弹时武器的垂直位置
settings.viewmodel.yOffADS 开镜时武器的垂直位置
settings.viewmodel.adsFovMlt 开镜放大倍数
settings.editing.header 编辑
settings.editing.health.high HUD 血条颜色(高)
settings.editing.health.low HUD 血条颜色(低)
settings.editing.speedLines 速度线(高速移动时显示速度线)
settings.editing.spdLinesCol 速度线颜色
settings.editing.score.color 弹出得分颜色
settings.editing.score.show 显示弹出得分
settings.editing.score.scale 弹出得分倍率
settings.editing.score.shadow 弹出得分阴影
settings.editing.scoreOffX 弹出得分X轴坐标
settings.editing.scoreOffY 弹出得分Y轴坐标
settings.editing.prog.color 进度条颜色
settings.editing.prog.opacity 进度条透明度
settings.editing.prog.scale 进度条大小
settings.editing.prog.shadow 进度条阴影
settings.editing.progOffX 进度条水平位置
settings.editing.progOffY 进度条垂直位置
settings.editing.progRot 进度条角度
settings.editing.progm.color 蓄力条颜色
settings.editing.progm.opacity 蓄力条透明度
settings.editing.progm.scale 蓄力条大小
settings.editing.progm.shadow 蓄力条阴影
settings.editing.progmOffX 蓄力条水平位置
settings.editing.progmOffY 力条垂直位置
settings.editing.progmRot 蓄力条角度
settings.editing.saturation 饱和度 (游戏中)
settings.editing.menuSaturation 饱和度 (用户界面)
settings.editing.hue 色调 (游戏中)
settings.editing.menuHue 色调 (用户界面)
settings.editing.vignette 晕影效果（使屏幕边缘颜色变暗)
settings.editing.feedLimit 击杀列表长度限制
settings.editing.depth 深度图模式
settings.editing.green 绿幕模式
settings.editing.tracercol 弹道轨迹
settings.editing.tracer 弹道轨迹
settings.editing.tracer.offset 弹道显示位置
settings.shaders.header 着色器输入
settings.mods.header 自定义
settings.mods.load 加载模组
settings.mods.logo 允许模组变更界面图标
settings.mods.auto 自动加载模组
settings.mods.borders 狙击镜边界
settings.mods.borderCol 狙击镜边界
settings.mods.borderOpac 狙击镜边界透明度
settings.mods.scope 狙击镜准心图标
settings.mods.scope.paste 狙击镜准心图标网址
settings.mods.scope.opacity 狙击镜准心透明度
settings.mods.scope.width 狙击镜准心宽度
settings.mods.scope.height 狙击镜准心高度
settings.mods.dot 准星图标
settings.mods.dot.width 准星图标宽度
settings.mods.dot.height 准星图标高度
settings.mods.dot.paste 准星图标网址
settings.mods.endmessage 比赛结束后自动消息
settings.mods.profile 用户图标
settings.mods.profile.paste 用户图标网址
settings.mods.ammo 弹药图标
settings.mods.ammo.paste 弹药图标网址
settings.mods.kills 击杀图标
settings.mods.kills.paste 击杀图标网址
settings.mods.deaths 死亡图标
settings.mods.deaths.paste 死亡图标网址
settings.mods.streak 连杀图标
settings.mods.streak.paste 连杀图标网址
settings.mods.timer 时钟图标
settings.mods.timer.paste 时钟图标网址
settings.mods.usedamage 覆盖受伤屏幕效果
settings.mods.damage 受伤屏幕效果图标
settings.mods.damage.paste 受伤屏幕效果网址
settings.mods.overlay 游戏结束图标
settings.mods.overlay.paste 游戏叠层图片网址
settings.social.region 各地区统计数据
windows.settings.header 游戏设定
windows.mail.header Krunker邮箱
windows.servers.header 服务器
windows.servers.none 无可加入游戏...
windows.servers.host + 创建游戏
windows.servers.hide 隐藏已满
windows.servers.priority 优先区域
windows.servers.online {0} 人正在游戏中
windows.servers.social {0} 正在游戏社交网站浏览中
windows.loadout.header 更换角色
windows.loadout.class 角色
windows.loadout.primary 主武器
windows.loadout.primary.attach 配件
windows.loadout.primary.reticle 准星
windows.loadout.primary.scope 狙击镜准心
windows.loadout.secondary 副武器
windows.loadout.secondary.skin 副武器皮肤
windows.loadout.melee 近战武器
windows.loadout.hat 头饰
windows.loadout.back 背部饰品
windows.loadout.waist 腰部饰品
windows.loadout.shoe Shoes 鞋子
windows.loadout.face 表情
windows.loadout.spray 涂鸦
windows.loadout.color.skin 皮肤颜色
windows.loadout.color.chat 聊天框中玩家用户名颜色
windows.loadout.color.hair 头发颜色
windows.loadout.dye 服装
windows.loadout.pet Pet 宠物
windows.loadout.stat 击杀统计卡
windows.loadout.flag 国家旗帜
windows.mods.drop 将模组文件放在此处或单击
windows.mods.paste 粘贴模组网址
windows.mods.load 加载模组
windows.mods.none 没有找到任何模组
windows.mods.header 模组管理器
windows.mods.guide 模组指南
windows.mods.list 模组列表
windows.mods.load.header 加载模组
windows.mods.publish 发布模组
windows.mods.viewer 观看者
windows.account.header 帐号
windows.account.recover 联系 <a>recovery@yendis.ch</a> 找回账号密码
windows.class.header 选择角色
windows.controls.header 更改控制
windows.controls.forward 前
windows.controls.backward 后
windows.controls.left 左
windows.controls.right 右
windows.controls.reload 重新装填
windows.controls.aim 瞄准
windows.controls.shoot 射击
windows.controls.inspect 查看武器
windows.controls.spray 涂鸦
windows.controls.jump 跳
windows.controls.crouch 蹲/滑铲
windows.controls.prim 主武器
windows.controls.swap 副武器
windows.controls.melee 近战武器
windows.controls.equip 装备
windows.controls.chat 文字聊天
windows.controls.voice 语言聊天
windows.controls.list 玩家列表
windows.controls.board 排行榜
windows.controls.interact 交互
windows.controls.interactSec 次要交互
windows.controls.confirm 确认交互
windows.controls.drop 放下(武器/物品)
windows.controls.wepVis 切换武器可见度
windows.controls.streak0 连杀 1
windows.controls.streak1 连杀 2
windows.controls.streak2 连杀 3
windows.controls.streak3 连杀 4
windows.controls.streak4 连杀 5
windows.controls.premium0 穿墙模式
windows.controls.premium1 无敌
windows.controls.premium2 击杀
windows.controls.premium3 重击
windows.controls.reset 重设时复活的位置（仅限于跑酷/速度竞赛模式）
windows.controls.pretend 隐藏游戏
windows.host.header 创建自定义游戏
windows.host.maps 服务器设定
windows.host.cmaps 社区游戏
windows.host.raw 原始游戏数据
windows.host.modes 选择模式
windows.host.classes 选择角色
windows.host.settings 服务器设定
windows.host.preset 创建预设
windows.host.preset.load 加载预设中...
windows.host.preset.name 预设名称
windows.host.start 开始游戏
windows.host.rehost 请重新开始游戏
windows.spray.header 选择涂鸦
windows.spray.default 默认涂鸦
windows.spray.spin 涂鸦
windows.maps.header 自定义游戏
windows.maps.none 没有找到游戏!
windows.maps.name 游戏名称
windows.maps.editor 游戏编辑器
windows.maps.publish 发布游戏
windows.maps.community 开发者社区
windows.publish.map.header 发布或更新游戏
windows.publish.map.thumbnail 没有缩略图
windows.publish.map.paste 粘贴游戏数据
windows.publish.map.update 发布/更新
windows.publish.map.login 创建并上传您的地图！
windows.theatre.header 影院模式
windows.theatre.record 启用录制
windows.theatre.key 录制按键
windows.clans.header 战队
windows.clans.members 战队成员 ({0})
windows.clans.requests 申请加入战队
windows.clans.requests.none 没有申请
windows.clans.page [{0}] 战队页面
windows.clans.create 创建工战队
windows.clans.name 战队名称
windows.clans.view 浏览战队
windows.clans.join 加入战队
windows.clans.login 创建并加入战队!
windows.store.header 商城
windows.store.spin {0} 转盘（开箱）
windows.store.agree 通过此次购买，您将同意 {0} 条款.
windows.store.purchase 购买KR
windows.store.voucher 兑换代金券
windows.store.voucherinfo 从指定主播和活动获取代金券
windows.store.market 市场
windows.store.market2 Krunker市场
windows.store.premium 购买Premium
windows.store.premium2 Krunker Premium
windows.store.buyP 在购买Premium后，您将可以自定义您的游戏用户名+体验更多专用功能！
windows.store.buy 买卖物品
windows.store.wheels 转盘
windows.store.unlock 解锁新武器和物品
windows.store.amount 账户中有 {0} KR 剩余
windows.store.login 用于在商店中购买和解锁物品!
windows.store.purchasing 购买中...
windows.store.unboxed {0}开箱解锁了{1}
windows.trade.header 交易
windows.scope.header 选择您的狙击镜准心
windows.premium.header Premium
windows.skin.header 选择皮肤
windows.hat.header 选择头部
windows.back.header 选择背部饰品
windows.waist.header 选择腰部饰品
windows.face.header 选择表情
windows.melee.header 选择近战武器
windows.attach.header 选择附件
windows.reticle.header 选择准星
windows.reticle.unlocked 于{0}级解锁
windows.reticle.req 需要{0}级
windows.dye.header 选择衣服
windows.dye.default 默认衣服
windows.dye.spin 衣服
windows.changelog.header 变更日志
windows.mods.community.header 社区模组
windows.mods.community.fav 最爱
windows.mods.community.new 最新模组
windows.mods.community.hot 最热门
windows.mods.community.name 模组名称
windows.mods.community.none 没有找到该模组
windows.publish.mod.header 发表模组
windows.publish.mod.thumbnail 没有缩略图
windows.publish.mod.name 模组名称
windows.publish.mod.paste 模组网址
windows.publish.mod.update 发表/更新
windows.publish.mod.login 以创建并上传!
windows.secondary.header 选择次要武器
windows.secondary.unlocked 已解锁
windows.secondary.req 需要至少{0}级
windows.advertise.header 广告
windows.support.header 支持
windows.players.header 玩家列表
windows.players.none 当前没有玩家...
windows.join.header 加入
windows.join.code 输入房间网址
windows.client.header 客户端
windows.client.windows Windows游戏安装包
windows.client.mac macOS游戏安装包
windows.client.linux Linux游戏安装包
windows.ranked.header 排位赛
windows.ranked.login 登录以进行排位赛!
windows.ranked.level 您至少需要 <span color="black"> {0} 级</span> 以进行排位赛! 当前您的等级是 <span color="black"> {1} 级</span>.
windows.ranked.mode.r1v1 单排
windows.ranked.mode.r2v2 双排
windows.ranked.mode.r4v4 四排
windows.chall.header 挑战
windows.chall.login 登录以完成挑战!
thumbnail.upload.limit 上传失败. 最大缩略图限制为｛0｝KB。
image.upload.limit 上传失败，最大图片限制为｛0｝KB。
thumbnail.upload.error 缩略图错误
mod.extracting 提取中 {0}/{1}
mod.disabled 模组已禁用
mod.error 模组错误!
mod.loading 加载模组中...
mod.invalid 无效模组文件!
matchmaker.full 满
matchmaker.full2 游戏已满.
matchmaker.updating 游戏更新中
matchmaker.invalid 没有找到游戏.
matchmaker.none 服务器已达上限
adblocker 禁用广告拦截器以获得免费的KR.
ad-failed 广告加载失败. 请稍后重试.
streamers.views {0} 观看者
streamers.none 当前没有Twitch直播!
error.extentions 如果您有任何(浏览器)插件, 请禁用它们
error.seek 点此以搜索新的游戏
custom.map.upload.limit 上传失败. 角色游戏数据限制为500kb
custom.map.missing 请选择至少一种游戏或地图
custom.mode.missing 请选择至少一种模式
custom.class.missing 请选择至少一种角色
server.config.maxPlayers 最大玩家数
server.config.minPlayers 最小玩家数
server.config.lives 玩家生命数
server.config.gameTime 每局时间(分钟)
server.config.gravMlt 重力
server.config.tickRI 高传送率
server.config.maxPS 40 名玩家服务器
server.config.promServ 推广服务器
server.config.jumpMlt 跳跃力量
server.config.airStrf 空中加速
server.config.deltaMlt 时间倍率
server.config.strafeSpd Strafe 速度
server.config.fiRat 武器射速
server.config.reSpd 换弹速度
server.config.slidTime 滑铲时间
server.config.fixMov 修复的运动动作
server.config.slidSpd 滑铲速度
server.config.healthMlt 血量倍率
server.config.impulseMlt 武器后坐力
server.config.nameTeam1 队伍 1 名字
server.config.nameTeam2 队伍 2 名字
server.config.nameTeam3 队伍 3 名字
server.config.nameTeam4 队伍 4 名字
server.config.nameTeam5 队伍 5 名字
server.config.t1Dmg 队伍 1 伤害
server.config.t2Dmg 队伍 2 伤害
server.config.t3Dmg 队伍 3 伤害
server.config.t4Dmg 队伍 4 伤害
server.config.t5Dmg 队伍 5 伤害
server.config.selTeam 选择队伍
server.config.allowSpect 观战
server.config.killRewards 击杀奖励
server.config.headshotOnly 仅限爆头模式
server.config.noSecondary 禁用服务器
server.config.noStreaks 禁用连杀
server.config.canSlide 可以滑铲
server.config.wallJP 墙壁跳跃倍率
server.config.autoJump 自动跳跃
server.config.bDrop 子弹下坠
server.config.thirdPerson 第三人称
server.config.requireCaptcha 需要Captcha验证
server.config.nameTags 隐藏名牌
server.config.kCams 玩家死亡视角
server.config.noReload 无需重装弹药
server.config.private 私人房间
server.config.krRewards KR 奖励
server.config.forceDefault 必须使用默认设置
server.config.warmupTime 热身时间
server.config.objtvTime 得分点存在时间
server.config.forceSpawn 自动重生时间
server.config.scoreLimit 得分限制
server.config.keepTScore 保持该队伍分数
server.config.forceC 必须使用特定武器
server.config.logTim 通关计时
server.config.hitBoxPad 碰撞箱大小
server.config.hpRegen 血量回复
server.config.disableB 解除地图边界
server.config.throwMel 投掷近战武器
server.config.noCosm 禁用饰品
social.login 登录/注册
social.login.failed 登录失败
social.login.buy 登录后购买
social.login.sell 登录后出售
social.login.gift 登录后赠送
social.login.proccessing 登录中...
social.since 自从
social.user.maps 用户的地图
social.user.mods 用户的模组
social.maps.none 没有找到游戏...
social.mods.none 没有找到模组...
social.market.price.low 最低价格
social.market.price.list 输入价格
social.market.searching 搜索
social.market.listed {0}前上架
social.market.list 上架物品
social.market.unlist 下架物品
social.market.unlisting 下架物品中...
social.market.posting 发布中...
social.market.req 需要至少{0}级
social.market.cant KR不足
social.market.purchase 购买
social.market.fee 无上架费用
social.market.failed 失败. 请稍后重试
social.market.head 头饰
social.market.back 背部饰品
social.market.waist 腰部饰品
social.market.face 表情
social.market.shoe 鞋子
social.market.pet 宠物
social.market.melee 近战武器
social.market.spray 涂鸦
social.market.dye 衣服
social.market.none 没有找到该物品
social.market.login 您必须先登录.
social.market.grace {0}秒后生效
social.market.sort 筛选/排序
social.market.filter 搜索
social.market.sort2 排序
social.market.price.high 最高价格
social.trading.submitting 提交报价中...
social.market.gift.amount 赠送金额
social.market.fee.gift 无费用
social.market.gift 赠送KR
social.market.gift.msg 留言
respawn.auto 您将会在｛0｝秒内重生
custom.host.ranked 您不可以在排位赛进行时开设自定义房间。
funds.insufficient 经费不足
funds.out 您似乎没有KR了。
custom.passcode.long 密码过长
custom.passcode.input 请输入房间密码
custom.tryagain 请重试。
purchase.kr.success 已成功将｛0｝KR加入您的账号
limited.purchase.ask 您确定您要以｛1｝KR购买｛0｝吗？
limited.purchase.success 以成功将｛0｝加入您的账号。
pretend.exit 再次点击[{0}]以退出
settings.loaded 设置已加载
settings.loaded.none 该设置并不存在
account.login.required 您必须先登录
account.banned.hack 此账号已因为使用外挂被禁赛。
account.banned.appeal 如果您认为您的账号被误封，请联系：
account.delete 如果您的账号删除申请在14天內没有被撤销，所有关于此账号的信息将会被删除。
account.delete.request 您确定您要申请账号删除吗？
account.delete.cancel 您确定您要撤销账号删除申请吗？
spin.free.available 免费KR已准备好！
spin.free.claim  此转盘仅可在每小时完成一局比赛后获得。
spin.free.disable 免费KR弹窗可以在设置中禁用。
mod.reset.0 该设置将会在玩家重生后生效。
mod.reset.1 地图将不会被重设。
windows.profile.picture 更改头像
stats.assists 助攻数
stats.nukes 使用核弹数
stats.melee 近战击杀数
stats.fistkills 空手击杀数
stats.thrownkills 投掷近战武器击杀数
stats.headshots 暴击数
stats.wallbangs 穿墙击杀数
stats.sprays 涂鸦次数
windows.host.default.settings 保持玩家计分功能仅可在使用默认设置时被打开
windows.host.default.commands 房主指令（比如/god, /smite, /noclip, 等等）将会在此模式中被禁用。
windows.host.rewards 打开KR奖励功能后，玩家可以在地图内获得KR奖励, 但是自定义设置将会被禁用。
windows.store.wheels.sub 试试这些转盘，您将会有机会获得全新皮肤！
windows.store.currency  *美元和您所在地区货币的汇率将会由支付服务提供商或您使用的银行决定
windows.store.creator 在购买KR时，请考虑使用创作者专用码以支持我们的视频/地图/模组创作者。
windows.chall.customs 您不可在自定义房间中完成挑战。
twitch.link 您确定您要链接您的Twitch账号吗？
twitch.unlink 您确定要取消链接吗？
windows.clan.leave 您确定您要离开该战队吗？
windows.clan.delete 您确定您要解散该战队吗？
windows.clan.kick 您确定您要将｛0｝踢出您的战队吗？
windows.store.premium.purchase 您确定您要购买｛0｝天的Premium吗？
windows.playerlist.ban 您确定要将｛0｝禁赛吗？
windows.playerlist.flag 您确定您要标记｛0｝为使用外挂吗?
windows.playerlist.unflag 您确定您要取消标记｛0｝吗?
windows.playerlist.punish 您确定您要对｛0｝采取此措施吗？
`;
