module.exports = `
menu.btn.ranked 排位賽
menu.btn.shop 商城
menu.btn.social 社區
menu.btn.maps 地圖
menu.btn.mods 插件
menu.btn.settings 設置
menu.btn.customize 自定義
menu.btn.invite 邀請
menu.btn.invite.clicked 已複製
menu.btn.join 加入遊戲
menu.btn.host 建立遊戲
menu.btn.browser 瀏覽伺服器
generic.wait 請稍等...
generic.loading 載入中...
generic.none 無
generic.connecting 連接中...
generic.select 選擇
generic.delete 刪除
generic.save 保存
generic.load 載入
generic.search 搜索
generic.leave 退出
generic.default 預設
generic.submit 提交
generic.create 創建
generic.random 隨機
generic.failed 失敗
generic.success 成功！
generic.name 用戶名
generic.level 等級
generic.score 得分
generic.off 關
generic.defeat 失敗
generic.victory 勝利
generic.matchover 比賽結束
generic.matchaband 比賽被迫終止
generic.follow 關注
generic.unfollow 取消關注
generic.followers 追隨者
generic.following 關注中
generic.games 遊戲
generic.wins 勝場
generic.lose 敗場
generic.clan 公會
generic.games.played 已玩遊戲
generic.games.won 勝場
generic.games.lost 敗場
generic.timep 遊玩時間
generic.kills 擊殺
generic.deaths 死亡
generic.kdr 擊殺死亡比例
generic.time 時間
generic.logout 登出
generic.logout.sessions 從所有設備登出
generic.username 輸入用戶名
generic.password 輸入密碼
generic.register 註冊
generic.login 登入
generic.accuracy 命中率
player.waiting 等待更多玩家加入
player.died 死亡
player.killed 被此玩家擊殺
player.killstreak {0} 正在 {1} 連殺
player.inactive 由於不活躍，遊戲已斷開連接
player.disconnect 連接已斷開
timer.end 下一場將在 {0} 後開始
leaderboard.empty 空房間
popup.checkpoint 存檔點！
app.play 點此開始遊戲
app.spectate 點此觀戰此局遊戲
app.play.mobile 輕點以開始遊戲
app.spectate.mobile 輕點以觀戰此局遊戲
app.play.controller 按下開始
app.spectate.controller 按下開始以觀戰此局遊戲
purchase.error 出現錯誤
purchase.error.click 點此</a> 並重試！
purchase.error.limit 您可能已超出每日交易限額
settings.reset 重置
settings.reset.confirm 您是否希望重置所有設定？
settings.import 匯入
settings.export 匯出
settings.none 沒有找到設定
settings.backup 備份設定
settings.controls.change 按鍵綁定
settings.controls.press 按下任意按鍵
settings.local.header 本地化 <span id="requiresRestart"><span style="color: #eb5656">*</span> 需要重啟遊戲</span>
settings.local.region 默認區域
settings.local.lang 語言
settings.network.header 網路
settings.network.sendRate 高伺服器應答率
settings.network.netRerouting 自動
settings.network.lagComp 延遲修正（Lag Compensation）
settings.popup.header 彈出視窗
settings.popup.freeKRPop 顯示免費KR彈出視窗
settings.experimental.header 實驗性功能
settings.experimental.aimFreezeFix 瞄準凍結修復
settings.experimental.mouseFlickFix 滑鼠過激修正
settings.experimental.shaderRendering 即時渲染
settings.dev.header 開發者
settings.dev.forceUpdate 強制刷新皮膚
settings.dev.forceRegen 永遠強制性復活玩家
settings.dev.extraBan 額外的封號資訊
settings.chat.header 聊天
settings.chat.chat 顯示聊天視窗
settings.chat.chat.all 總是
settings.chat.chat.focus 僅限關注時顯示
settings.chat.messages 顯示玩家消息
settings.chat.unboxings 顯示開箱
settings.chat.chatOp 聊天視窗透明度
settings.chat.chatBGOp 聊天視窗背景透明度
settings.chat.chatHeight 聊天視窗高度
settings.chat.chatTimer 消息顯示時間
settings.chat.chatTextOutline 消息文字輪廓
settings.chat.chatFilter 不良語言過濾（僅限英文）
settings.quality.header 遊戲性能
settings.quality.updRate 幀數限制
settings.quality.rendDst 渲染距離
settings.quality.res 解析度
settings.quality.part 粒子效果
settings.quality.mapDet 地圖細節
settings.quality.noTex 無貼圖
settings.quality.partdist 粒子渲染距離
settings.quality.renderdist 渲染距離
settings.quality.reflection 倒影品質
settings.quality.antiAlias 除鋸齒
settings.quality.shadows 陰影
settings.quality.softShad 軟陰影
settings.quality.highResShad 高解析度陰影
settings.quality.shadowsDynamic 動態陰影
settings.quality.trails 其他玩家彈道軌跡
settings.quality.yourTrails 玩家自身彈道軌跡
settings.quality.mflash 槍口火焰
settings.quality.flap 狙擊槍瞄準鏡保護蓋
settings.quality.lowSpec 低配置模式
settings.quality.ambient 環境陰影
settings.quality.ambientOld 舊版陰影畫風 （僅當可能時）
settings.quality.textureAnim 紋理動畫
settings.quality.objectAnim 物體動畫
settings.quality.screenShake 螢幕晃動
settings.quality.weaponShine 武器光澤
settings.quality.rendGamma 伽馬效果
settings.quality.lighting 光照效果
settings.quality.showExplo 顯示爆炸
settings.quality.aspectRatio 螢幕高寬比
settings.post.header 後期處理
settings.post.post 後期處理
settings.post.bloom 光散射
settings.post.bloomThreshold 光散射閾值
settings.post.bloomStrength 光散射強度
settings.post.bloomRadius 光散射半徑
settings.post.ssao 螢幕空間環境光遮罩
settings.post.ssaoRadius 螢幕空間環境光屏蔽半徑
settings.interface.hitInd 受擊提示
settings.interface.hitColor 受擊提示顏色
settings.interface.dmg 顯示傷害
settings.interface.dmgCol 傷害顏色
settings.interface.critCol 暴擊顏色
settings.interface.header 介面
settings.interface.scale 用戶介面比例
settings.interface.ui 顯示用戶介面
settings.interface.scoreboard 使用經典計分板
settings.interface.oldBrowser 使用經典伺服器瀏覽器
settings.interface.rarityanim 禁用稀有物品動畫
settings.interface.showPfp 顯示用戶圖示
settings.interface.showTradeMsg 顯示交易消息
settings.interface.hp 動態血條（HP）
settings.interface.dmgScale 傷害顯示比例
settings.interface.killf 顯示擊殺清單
settings.interface.ping 顯示延遲（PING）
settings.interface.net-stats 顯示網路狀況
settings.interface.fps 顯示幀率（FPS）
settings.interface.deaths 顯示死亡數
settings.interface.kd 顯示死亡擊殺比例
settings.interface.kills 顯示擊殺數
settings.interface.streak 顯示連殺數
settings.interface.score 顯示分數
settings.interface.spectators 顯示觀戰者
settings.interface.speed 顯示移動速度
settings.interface.speedOffX 移動速度X軸座標
settings.interface.speedOffY 移動速度Y軸座標
settings.interface.speedOpacity 速度顯示透明度
settings.interface.speedScale 速度顯示比例
settings.interface.speedColor 當前速度顏色
settings.interface.speedColorMax 最高速度顏色
settings.interface.medals 顯示勳章
settings.interface.hideNames 顯示名牌
settings.interface.hideNames.team 僅限隊友
settings.interface.hideNames.enemy 僅限敵人
settings.interface.hideNames.all 所有人
settings.interface.nametagStyle 名牌樣式
settings.interface.nametagOpac 名牌透明度
settings.interface.nametagStyle.health 僅限血條（HP）
settings.interface.nametagStyle.name 僅限姓名
settings.interface.nametagStyle.nameLvl 姓名和血條（HP）
settings.interface.nametagStyle.all 所有
settings.interface.healthNum 名牌
settings.interface.healthColT 隊友血條（HP）顏色
settings.interface.healthColE 敵人血條（HP）顏色
settings.interface.xpBarCol 經驗條顏色
settings.interface.xpBarOpac 經驗條透明度
settings.crosshair.header 準星
settings.crosshair.type 種類
settings.crosshair.type.2 自定義
settings.crosshair.type.3 疊層
settings.crosshair.type.4 圖片
settings.crosshair.type.5 精準
settings.crosshair.style 樣式
settings.crosshair.style.0 十字
settings.crosshair.style.1 空心圓
settings.crosshair.style.2 實心圓
settings.crosshair.style.3 空心方塊
settings.crosshair.style.4 實心方塊
settings.crosshair.image 圖片
settings.crosshair.image.paste 準星圖片
settings.crosshair.always 總是顯示
settings.crosshair.color 顏色
settings.crosshair.shadow.color 陰影顏色
settings.crosshair.shadow.thickness 陰影粗細
settings.crosshair.size 尺寸
settings.crosshair.thickness 粗細
settings.crosshair.gap 中心間隔大小
settings.crosshair.dot 點
settings.crosshair.opacity.use 使用自定義透明度
settings.crosshair.opacity.custom 自定義透明度
settings.hitmarker.header 命中標記
settings.hitmarker.color 顏色
settings.hitmarker.kcolor 擊殺顏色
settings.hitmarker.thickness 粗細
settings.hitmarker.opacity 透明度
settings.hitmarker.leng 長度
settings.hitmarker.spacing 間距
settings.hitmarker.animD 動畫尺寸
settings.hitmarker.animS 動畫速度
settings.hitmarker.hitm 顯示
settings.hitmarker.hitmFad 褪去速度
settings.hitmarker.custom 命中標記圖示
settings.hitmarker.custom.paste 命中標記網址
settings.onKillS.style.0 預設
settings.onKillS.style.1 降低解析度
settings.onKillS.style.2 降低視野範圍
settings.onKillS.style.3 增加視野範圍
settings.serverb.header 伺服器引擎
settings.serverb.oldBrowser 舊版伺服器引擎展示風格
settings.serverb.defaultRegionOnly 僅顯示預設地區伺服器
settings.gameprivacy.header 遊玩隱私
settings.gameprivacy.streamer 主播模式
settings.gameprivacy.anon 匿名模式
settings.gameprivacy.hideGameTitle 隱藏遊戲名稱
settings.gameplay.header 遊戲性
settings.gameplay.sensitivityX X軸靈敏度
settings.gameplay.sensitivityY Y軸靈敏度
settings.gameplay.aimsensX 瞄準X軸靈敏度
settings.gameplay.aimsensY 瞄準Y軸靈敏度
settings.gameplay.challenge 挑戰模式
settings.gameplay.invert 反轉Y軸
settings.gameplay.onkillS 擊殺
settings.gameplay.scrollDir 滑鼠滾輪方向
settings.controller.header 手柄
settings.controller.sensitivityX X軸靈敏度
settings.controller.disableCons 關閉手柄
settings.controller.sensitivityY Y軸靈敏度
settings.controller.aimsensX 瞄準X軸靈敏度
settings.controller.aimsensY 瞄準Y軸靈敏度
settings.controller.deadZoneL 手柄搖桿死區 （左）
settings.controller.deadZoneR 手柄搖桿死區 （右）
settings.controller.triggerThres 觸發閾值
settings.controller.vibration 震動
settings.controller.gradSpeed 漸緩速度
settings.controller.invert 反轉Y軸
settings.mobile.header 行動裝置
settings.mobile.sensitivityX X軸靈敏度
settings.mobile.sensitivityY Y軸靈敏度
settings.mobile.aimsensX 瞄準X軸靈敏度
settings.mobile.aimsensY 瞄準Y軸靈敏度
settings.mobile.vibration 震動
settings.mobile.gradSpeed 漸緩速度
settings.mobile.invert 反轉Y軸
settings.audio.header 音訊
settings.audio.sound 主音量
settings.audio.ambient 環境音量
settings.audio.voice 語言音量
settings.audio.weps 武器音量
settings.audio.player 玩家音量
settings.audio.skin 裝扮音量
settings.audio.ui 用戶介面音量
settings.audio.asset 地圖元件音量
settings.audio.dialogue 動作音量
settings.viewmodel.header 視角
settings.viewmodel.fov 視野範圍
settings.viewmodel.fps 武器渲染視野範圍
settings.viewmodel.bobbing 武器晃動
settings.viewmodel.leaning 武器傾斜
settings.viewmodel.show.primary 顯示主武器
settings.viewmodel.show.secondary 顯示副武器
settings.viewmodel.roundArms 圓柱形手臂
settings.viewmodel.show.melee 顯示近戰武器
settings.viewmodel.show.ads 瞄準時隱藏武器
settings.viewmodel.toggleAim 切換瞄準
settings.viewmodel.show.hands 顯示手部
settings.viewmodel.leftHand 左手模式
settings.viewmodel.aimAnim 武器瞄準動畫
settings.viewmodel.rot 武器旋轉
settings.viewmodel.xOff 武器X軸座標
settings.viewmodel.yOff 武器Y軸座標
settings.viewmodel.zOff 武器Z軸座標
settings.viewmodel.weapSwapY 武器切換時的Y軸座標
settings.viewmodel.weapReloadY 武器切換時的Y軸座標
settings.viewmodel.yOffADS 武器瞄準Y軸座標
settings.viewmodel.adsFovMlt 瞄準視野範圍倍率
settings.editing.header 編輯
settings.editing.health.high 血條顏色（高）
settings.editing.health.low 血條顏色（低）
settings.editing.speedLines 速度線（高速移動時顯示速度線）
settings.editing.spdLinesCol 速度線顏色
settings.editing.score.color 彈出得分顏色
settings.editing.score.show 顯示彈出得分
settings.editing.score.scale 彈出得分倍率
settings.editing.score.shadow 彈出得分陰影
settings.editing.scoreOffX 彈出得分X軸座標
settings.editing.scoreOffY 彈出得分Y軸座標
settings.editing.prog.color 經驗條顏色
settings.editing.prog.opacity 進度條透明度
settings.editing.prog.scale 進度條大小
settings.editing.prog.shadow 進度條陰影
settings.editing.progOffX 進度條水準位置
settings.editing.progOffY 進度條垂直位置
settings.editing.progRot 進度條角度
settings.editing.progm.color 蓄力條顏色
settings.editing.progm.opacity 蓄力條透明度
settings.editing.progm.scale 蓄力條大小
settings.editing.progm.shadow 蓄力條陰影
settings.editing.progmOffX 蓄力條水準位置
settings.editing.progmOffY 蓄力條垂直位置
settings.editing.progmRot 蓄力條角度
settings.editing.saturation 飽和度（遊戲中）
settings.editing.menuSaturation 飽和度（用戶介面）
settings.editing.hue 色調（遊戲中）
settings.editing.menuHue 色調（用戶介面）
settings.editing.vignette 暈影效果（使螢幕邊緣顏色變暗）
settings.editing.feedLimit 擊殺列表長度限制
settings.editing.depth 深度圖模式
settings.editing.green 綠幕模式
settings.editing.tracercol 彈道軌跡
settings.editing.tracer 彈道軌跡
settings.editing.tracer.offset 瞄準器偏移
settings.shaders.header 著色器輸入
settings.mods.header 自定義
settings.mods.load 載入插件
settings.mods.logo 允許變更圖示
settings.mods.auto 自動載入插件
settings.mods.borders 瞄準鏡邊界
settings.mods.borderCol 狙擊鏡
settings.mods.borderOpac 狙擊鏡邊界透明度
settings.mods.scope 狙擊鏡圖示
settings.mods.scope.paste 狙擊鏡圖示網址
settings.mods.scope.opacity狙擊鏡透明度
settings.mods.scope.width 狙擊鏡寬度
settings.mods.scope.height 狙擊鏡高度
settings.mods.dot 準星圖示
settings.mods.dot.width 準星圖示寬度
settings.mods.dot.height 準星圖示高度
settings.mods.dot.paste 準星圖示網址
settings.mods.endmessage 比賽結束后自動消息
settings.mods.profile 用戶圖示
settings.mods.profile.paste 用戶圖示網址
settings.mods.ammo 彈藥圖示
settings.mods.ammo.paste 彈藥圖示網址
settings.mods.kills 擊殺圖示
settings.mods.kills.paste 擊殺圖示網址
settings.mods.deaths 死亡圖示
settings.mods.deaths.paste 死亡圖示網址
settings.mods.streak 連殺圖示
settings.mods.streak.paste 連殺圖示網址
settings.mods.timer 時鐘圖示
settings.mods.timer.paste 時鐘圖示網址
settings.mods.usedamage 覆蓋受傷螢幕效果
settings.mods.damage 受傷螢幕效果圖示
settings.mods.damage.paste 受傷螢幕效果網址
settings.mods.overlay 遊戲結束圖示
settings.mods.overlay.paste 遊戲疊層圖片網址
settings.social.region 地區統計
windows.settings.header 遊戲設定
windows.mail.header Krunker郵箱
windows.servers.header 伺服器
windows.servers.none 無可加入遊戲...
windows.servers.host + 創建遊戲
windows.servers.hide 隱藏已滿
windows.servers.priority 優先區域
windows.servers.online {0} 人在遊戲中
windows.servers.social {0} 人在社區中
windows.loadout.header 更換角色
windows.loadout.class 角色
windows.loadout.primary 主武器
windows.loadout.primary.attach 配件
windows.loadout.primary.reticle 準星
windows.loadout.primary.scope 狙擊瞄準鏡
windows.loadout.secondary 副武器
windows.loadout.secondary.skin 副武器皮膚
windows.loadout.melee 近戰武器
windows.loadout.hat 頭部
windows.loadout.back 身體
windows.loadout.waist 腰部
windows.loadout.shoe 鞋子
windows.loadout.face 表情
windows.loadout.spray 塗鴉
windows.loadout.color.skin 皮膚顏色
windows.loadout.color.chat 使用者名顏色
windows.loadout.color.hair 頭髮顏色
windows.loadout.dye 服裝
windows.loadout.pet 寵物
windows.loadout.stat 擊殺統計卡
windows.loadout.flag 國家旗幟
windows.mods.drop 將插件文檔放在此處/按一下
windows.mods.paste 粘貼插件網址
windows.mods.load 載入插件
windows.mods.none 沒有找到插件
windows.mods.header 插件管理器
windows.mods.guide 插件指南
windows.mods.list 插件清單
windows.mods.load.header 載入插件
windows.mods.publish 發佈插件
windows.mods.viewer 皮膚瀏覽器
windows.account.header 帳戶
windows.account.recover 聯繫 <a>krunker@yendis.ch</a> 以找回賬號密碼
windows.class.header 選擇角色
windows.controls.header 更改控制
windows.controls.forward 前
windows.controls.backward 後
windows.controls.left 左
windows.controls.right 右
windows.controls.reload 重新裝填
windows.controls.aim 瞄準
windows.controls.shoot 射擊
windows.controls.inspect 查看武器
windows.controls.spray 塗鴉
windows.controls.jump 跳
windows.controls.crouch 蹲
windows.controls.prim 主武器
windows.controls.swap 副武器
windows.controls.melee 近戰武器
windows.controls.equip 裝備
windows.controls.chat 文字聊天
windows.controls.voice 語言聊天
windows.controls.list 玩家清單
windows.controls.board 排行榜
windows.controls.interact 交互
windows.controls.interactSec 次要交互
windows.controls.confirm 確認互動
windows.controls.drop 放下（武器/物品）
windows.controls.wepVis 切換武器可見度
windows.controls.streak0 一連殺
windows.controls.streak1 二連殺
windows.controls.streak2 三連殺
windows.controls.streak3 四連殺
windows.controls.streak4 五連殺
windows.controls.premium0 穿牆模式
windows.controls.premium1 無敵模式
windows.controls.premium2 擊殺（自己）
windows.controls.premium3 重擊模式
windows.controls.reset 返回起點（競賽和跑酷）
windows.controls.pretend 隱藏遊戲
windows.host.header 創建自定義遊戲
windows.host.maps 伺服器設定
windows.host.cmaps 社區遊戲
windows.host.raw 原始遊戲數據
windows.host.modes 選擇模式
windows.host.classes 選擇角色
windows.host.settings 伺服器設定
windows.host.preset 創建預設
windows.host.preset.load 載入預設中...
windows.host.preset.name 預設名稱
windows.host.start 開始遊戲
windows.host.rehost 開始遊戲（帶入玩家）
windows.spray.header 選擇塗鴉
windows.spray.default 預設塗鴉
windows.spray.spin 塗鴉
windows.maps.header 自定義遊戲
windows.maps.none 沒有找到遊戲！
windows.maps.name 遊戲名稱
windows.maps.editor 遊戲編輯器
windows.maps.publish 發佈遊戲
windows.maps.community 開發者社區
windows.publish.map.header 發佈或更新遊戲
windows.publish.map.thumbnail 沒有縮略圖
windows.publish.map.paste 粘貼遊戲數據
windows.publish.map.update 發佈/更新
windows.publish.map.login 創建並上傳遊戲！
windows.theatre.header 影院模式
windows.theatre.record 啟用錄製
windows.theatre.key 錄製按鍵
windows.clans.header 公會
windows.clans.members 成員 （{0}）
windows.clans.requests 申請
windows.clans.requests.none 沒有申請
windows.clans.page [{0}] 公會頁面
windows.clans.create 創建公會
windows.clans.name 公會名稱
windows.clans.view 瀏覽公會
windows.clans.join 加入公會
windows.clans.login 創建並加入公會！
windows.store.header 商店
windows.store.spin {0} 旋轉/開箱
windows.store.agree 通過此次購買，您將同意 {0} 條款.
windows.store.purchase 購買KR
windows.store.voucher 兌換代金券
windows.store.voucherinfo 從指定主播和活動獲取代金券
windows.store.market 市場
windows.store.market2 Krunker市場
windows.store.premium 購買會員
windows.store.premium2 Krunker會員
windows.store.buyP 選擇顯示名稱以及更多內容
windows.store.buy 買賣物品
windows.store.wheels 獎輪
windows.store.unlock 解鎖新武器和物品
windows.store.amount 帳戶中有 {0} KR 剩餘
windows.store.login 用於在商店中購買和解鎖物品！
windows.store.purchasing 購買中...
windows.store.unboxed {0}開箱獲得了{1}
windows.trade.header 物品交易
windows.scope.header 選擇瞄準鏡
windows.premium.header 會員
windows.skin.header 選擇皮膚
windows.hat.header 選擇帽子
windows.back.header 選擇背部飾品
windows.waist.header 選擇腰部飾品
windows.face.header 選擇面部飾品
windows.melee.header 選擇近戰武器
windows.attach.header 選擇附件
windows.reticle.header 選擇準星
windows.reticle.unlocked 於{0}級結束
windows.reticle.req 需要{0}級
windows.dye.header 選擇服裝
windows.dye.default 默認服裝
windows.dye.spin 服裝
windows.changelog.header 變更日誌
windows.mods.community.header 社區插件
windows.mods.community.fav 最愛
windows.mods.community.new 最新插件
windows.mods.community.hot 最熱門
windows.mods.community.name 插件名稱
windows.mods.community.none 沒有找到插件
windows.publish.mod.header 發表插件
windows.publish.mod.thumbnail 沒有縮略圖
windows.publish.mod.name 插件名稱
windows.publish.mod.paste 插件網址
windows.publish.mod.update 發表/更新
windows.publish.mod.login 以創建並上傳！
windows.secondary.header 選擇次要武器
windows.secondary.unlocked 已解鎖
windows.secondary.req 需要至少{0}級
windows.advertise.header 廣告
windows.support.header 支援
windows.players.header 玩家清單
windows.players.none 目前沒有玩家...
windows.join.header 加入
windows.join.code 輸入遊戲 網址/代碼
windows.client.header 用戶端
windows.client.windows Windows遊戲安裝器
windows.client.mac macOS遊戲安裝器
windows.client.linux Linux遊戲安裝器
windows.ranked.header 排位
windows.ranked.login 以進行排位賽！
windows.ranked.level 您至少需要 <span color="black"> {0} 級</span> 以進行排位賽！ 目前您的等級是 <span color="black"> {1} 級</span>.
windows.ranked.mode.r1v1 單排
windows.ranked.mode.r2v2 雙排
windows.ranked.mode.r4v4 四排
windows.chall.header 挑戰
windows.chall.login 以完成挑戰！
thumbnail.upload.limit 失敗. {0}kb 縮略圖限制
image.upload.limit 失敗. {0}kb 圖片限制
thumbnail.upload.error 縮略圖錯誤
mod.extracting 提取中 {0}/{1}
mod.disabled 插件已關閉
mod.error 插件錯誤！
mod.loading 載入插件中...
mod.invalid 無效插件文檔！
matchmaker.full 滿
matchmaker.full2 遊戲已滿.
matchmaker.updating 遊戲更新中
matchmaker.invalid 找不到遊戲
matchmaker.none 伺服器已達上限
adblocker 停用廣告攔截器以取得免費的KR.
ad-failed 廣告載入失敗. 請稍後重試.
streamers.views {0} 個觀看者
streamers.none 當前沒有Twitch直播！
error.extentions 如果您有任何（瀏覽器）插件， 請關閉它們
error.seek 點此以搜索新的遊戲
custom.map.upload.limit 失敗. 遊戲數據限制為五十萬字元
custom.map.missing 請選擇至少一種遊戲或地圖
custom.mode.missing 請選擇至少一種模式
custom.class.missing 請選擇至少一種角色
server.config.maxPlayers 最大玩家數
server.config.minPlayers 最小玩家數
server.config.lives 生命數
server.config.gameTime 時間（分鐘）
server.config.gravMlt 重力
server.config.tickRI 高傳輸率（High Tickrate）
server.config.maxPS 40 名玩家伺服器
server.config.promServ 推廣伺服器
server.config.jumpMlt 跳躍力量
server.config.airStrf 空中轉向
server.config.deltaMlt 時間倍率
server.config.strafeSpd 空中轉向速度
server.config.fiRat 武器射速
server.config.reSpd 換彈速度
server.config.slidTime 滑動 時間
server.config.fixMov 完善動作
server.config.slidSpd 滑動速度
server.config.healthMlt 血量倍率
server.config.impulseMlt 武器後坐力
server.config.nameTeam1 隊伍 1 名字
server.config.nameTeam2 隊伍 2 名字
server.config.nameTeam3 隊伍 3 名字
server.config.nameTeam4 隊伍 4 名字
server.config.nameTeam5 隊伍 5 名字
server.config.t1Dmg 隊伍 1 傷害
server.config.t2Dmg 隊伍 2 傷害
server.config.t3Dmg 隊伍 3 傷害
server.config.t4Dmg 隊伍 4 傷害
server.config.t5Dmg 隊伍 5 傷害
server.config.selTeam 選擇隊伍
server.config.allowSpect 觀戰
server.config.killRewards 擊殺獎勵
server.config.headshotOnly 僅限爆頭模式
server.config.noSecondary 禁用伺服器
server.config.noStreaks 禁用連殺
server.config.canSlide 滑動
server.config.wallJP 牆壁跳躍倍率
server.config.autoJump 自動跳躍
server.config.bDrop 子彈下墜
server.config.thirdPerson 第三人稱
server.config.requireCaptcha 需要Captcha驗證
server.config.nameTags 隱藏名牌
server.config.kCams 死亡重播
server.config.noReload 無需重裝彈藥
server.config.private 私人
server.config.krRewards KR獎勵
server.config.forceDefault 強制預設設定
server.config.warmupTime 熱身時間
server.config.objtvTime 目標時間
server.config.forceSpawn 自動重生時間
server.config.scoreLimit 得分限制
server.config.keepTScore 保留隊伍分數
server.config.forceC 強制角色類別
server.config.logTim 記錄時間（競賽，跑酷）
server.config.hitBoxPad 擊中判斷模型倍率（hitbox）
server.config.hpRegen 血量回復
server.config.disableB 解除地圖邊界
server.config.throwMel 飛刀
server.config.noCosm 隱去裝扮
social.login 登錄/註冊
social.login.failed 登入失敗
social.login.buy 登錄後購買
social.login.sell 登錄後出售
social.login.gift 登錄後贈送
social.login.proccessing 登入中...
social.since 自從
social.user.maps 用戶遊戲
social.user.mods 使用者插件
social.maps.none 找不到遊戲...
social.mods.none 找不到插件...
social.market.price.low 最低價格
social.market.price.list 輸入價格
social.market.searching 搜索
social.market.listed {0}前上架
social.market.list 上架物品
social.market.unlist 下架物品
social.market.unlisting 下架物品中...
social.market.posting 發佈物品中...
social.market.req 需要至少{0}級
social.market.cant KR不足
social.market.purchase 購買
social.market.fee 無上架費用
social.market.failed 失敗. 請稍後重試
social.market.head 頭飾
social.market.back 背部飾品
social.market.waist 腰部飾品
social.market.face 表情
social.market.shoe 鞋子
social.market.pet 寵物
social.market.melee 近戰武器
social.market.spray 塗鴉
social.market.dye 服裝
social.market.none 沒有找到該物品
social.market.login 您必須先登錄
social.market.grace {0}秒後生效
social.market.sort 篩選/排序
social.market.filter 搜索
social.market.sort2 排序
social.market.price.high 最高價格
social.trading.submitting 提交報價中...
social.market.gift.amount 贈送金額
social.market.fee.gift 無費用
social.market.gift 贈送KR
social.market.gift.msg 留言
respawn.auto 您將會在{0}秒內自動重生
custom.host.ranked 排位賽正在進行，暫時不能開設房間
funds.insufficient 基金餘額不足
funds.out 您的KR餘額不足
custom.passcode.long 密碼過長
custom.passcode.input 請輸入房間密碼
custom.tryagain 請重試
purchase.kr.success 向您的帳號中添加了{0}KR
limited.purchase.ask 您確定要用 [{0}] 買 {1} KR？
limited.purchase.success 向您的帳戶中添加了{0}KR
pretend.exit 再次點擊 [{0}] 以退出
settings.loaded 設置載入完畢
settings.loaded.none 沒有發現設置
account.login.required 必須登錄
account.banned.hack 此帳號已因為使用外掛被封號
account.banned.appeal 如果您認為您被誤封，請聯絡：
account.delete 您可以請求刪除該帳號;如果此請求在十四天內沒有被撤回，該帳號與其所有相連的數據資訊將會被永久抹除
account.delete.request 您確定您要請求刪除該帳號嗎？
account.delete.cancel 您確定您要取消刪除該帳號嗎？
spin.free.available 可以獲取免費KR了！
spin.free.claim 該轉盤僅可在每小時完成一場比賽后使用一次
spin.free.disable 此彈窗可以在通用設置中被取消
mod.reset.0 將會在復活后產生效果
mod.reset.1 地圖物體將不會被重置
windows.profile.picture 更改頭像
stats.assists 助攻次數
stats.nukes 核彈次數
stats.melee 近戰擊殺
stats.fistkills 空手擊殺
stats.thrownkills 飛刀擊殺
stats.headshots 爆頭次數
stats.wallbangs 穿牆次數
stats.sprays 塗鴉次數
windows.host.default.settings 啟用預設設置可以存儲玩家進度和高分
windows.host.default.commands *房主專用指令如/noclip，/god，/smite等已關閉
windows.host.rewards 開啟KR獎勵機制將會強制啟用預設設定並且允許玩家從地圖基金中贏得KR：
windows.store.wheels.sub 試試您的運氣！ 轉動轉盤以贏得一些新皮膚！
windows.store.currency * 這些價格可以由付款提供者或銀行以匯率計算從美元轉換到您的當地貨幣
windows.store.creator 考慮通過使用您最喜歡的 Krunker 內容建立者的代碼支持他們
windows.chall.customs 挑戰不能在自定義遊戲內進行
twitch.link 您確定您要連結您的Twitch帳號嗎？
twitch.unlink 您確定您要取消連結您的Twitch帳號嗎？
windows.clan.leave 您確定您要離開此公會嗎？
windows.clan.delete 您確定您要刪除此公會嗎？
windows.clan.kick 您確定您要將{0}從此公會踢出嗎？
windows.store.premium.purchase 您確定您要購買 {0} 天的會員嗎？
windows.playerlist.ban 您確定您要將{0}從此局中封掉嗎？
windows.playerlist.flag 您確定您要標記{0}嗎？
windows.playerlist.unflag 您確定您要取消標記{0}嗎？
windows.playerlist.punish 您確定您要對{0}採取行動嗎？
